services:
  - type: web
    name: insight-forge-python-api
    env: python
    buildCommand: "cd worker-python && pip install -r requirements.txt"
    startCommand: "cd worker-python && uvicorn api:fastapi_app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: insight-forge-redis
          property: connectionString
      - key: MONGO_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false

  - type: worker
    name: insight-forge-celery-worker
    env: python
    buildCommand: "cd worker-python && pip install -r requirements.txt"
    startCommand: "cd worker-python && celery -A celery_app worker --loglevel=info"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: insight-forge-redis
          property: connectionString
      - key: MONGO_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false

  - type: redis
    name: insight-forge-redis
    ipAllowList: [] # only allow internal connections
    plan: free
